replaced USB_INTR_VECTOR by USB_handler, removed all eventually non standard optimisations (costs 10 bytes), changes for upstream, replace launcher by micronucleus, commented out push of Y

diff --git a/.github/workflows/BuildBinaries.yml b/.github/workflows/BuildBinaries.yml
--- a/.github/workflows/BuildBinaries.yml
+++ b/.github/workflows/BuildBinaries.yml
@@ -1,7 +1,7 @@
 # BuildBinaries.yml
-# Github workflow to build micronucleus binaries for  different platforms
+# Github workflow to build micronucleus binaries for different platforms
 #
-# Copyright (C) 2021  Armin Joachimsmeyer
+# Copyright (C) 2021  Armin Joachimsmeyer based on the valuable work of Thomas Quinot https://github.com/quinot
 # https://github.com/ArminJo/Github-Actions
 #
 name: BuildBinaries
@@ -11,94 +11,248 @@ on:
     paths:
     - '**/comandline/library/**'
     - '**/comandline/micronucleus.c'
-    - '**BuildBinaries.yml'
+#    - '**/comandline/builds/**/package.json'
+#    - '**BuildBinaries.yml'
 
 jobs:
-  build-all:
+  build-all-executables:
     strategy:
       matrix:
          include:
          - os: ubuntu-latest
-           shell: bash
+           target-dir: x86_64-linux-gnu
+           shell: bash {0}
+
+         - os: ubuntu-latest
+           target-dir: i686-linux-gnu
+           container: debian:buster
+           shell: bash {0}
+
+         - os: ubuntu-latest
+           target-dir: arm-linux-gnueabihf
+           container: debian:buster
+           shell: bash {0}
+
+         - os: ubuntu-latest
+           target-dir: aarch64-linux-gnu
+           container: debian:buster
+           shell: bash {0}
+
          - os: macos-latest
-           shell: bash
-#         - os: windows-2019
-#           shell: msys2 {0}
+           target-dir: x86_64-apple-darwin
+           shell: bash {0}
+
+         - os: windows-2019
+           shell: msys2 {0}
+           target-dir: i686-mingw32
+
+         - os: windows-2019
+           shell: msys2 {0}
+           target-dir: x86_64-mingw32
 
     runs-on: ${{ matrix.os }}
+    container: ${{ matrix.container }}
     defaults:
       run:
         shell: ${{ matrix.shell }}
 
     steps:
 
-    - uses: actions/checkout@v2
-      with:
-        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
-        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
-
-    - name: install Linux dependencies and run make
+    - name: install git for Linux container
+      if: runner.os == 'Linux'
       run: |
-        sudo sh -c "apt-get update && apt-get install libusb-dev"
+        if [[ -z "$(which git)" ]]; then
+          echo "installing missing git"
+          apt-get update
+          apt-get install --yes git
+          GIT_DIR=$GITHUB_WORKSPACE
+        fi
+
+    - uses: actions/checkout@v2
+
+    - name: install Linux 64 dependencies and run make
+      if: runner.os == 'Linux' && matrix.target-dir == 'x86_64-linux-gnu'
+      run: |
+        sudo apt-get update
+        sudo apt-get install libusb-dev
         cd commandline
         make
-        TARGET_DIR=Linux-x86_64
-        echo TARGET_DIR=$TARGET_DIR
-        if [[ ! -d builds/$TARGET_DIR/ ]]; then mkdir builds/$TARGET_DIR; fi
-        mv micronucleus builds/$TARGET_DIR
-      if: runner.os == 'Linux'
 
-    - name: Install Windows build system
+    - name: install Linux 32 dependencies and run make
+      if: runner.os == 'Linux' && matrix.target-dir == 'i686-linux-gnu'
+      run: |
+        ls -la $GITHUB_WORKSPACE
+        dpkg --add-architecture i386
+        apt-get update
+        echo apt-get install --yes make crossbuild-essential-i386 libusb-dev:i386
+        apt-get install --yes make crossbuild-essential-i386 libusb-dev:i386
+        cd commandline
+        make CC=i686-linux-gnu-gcc
+
+    - name: install Linux armhf dependencies and run make
+      if: runner.os == 'Linux' && matrix.target-dir == 'arm-linux-gnueabihf'
+      run: |
+        dpkg --add-architecture armhf
+        apt-get update
+        apt-get install --yes make crossbuild-essential-armhf libusb-dev:armhf
+        cd commandline
+        make CC=arm-linux-gnueabihf-gcc
+
+    - name: install Linux arm64 dependencies and run make
+      if: runner.os == 'Linux' && matrix.target-dir == 'aarch64-linux-gnu'
+      run: |
+        dpkg --add-architecture arm64
+        apt-get update
+        apt-get install --yes make crossbuild-essential-arm64 libusb-dev:arm64
+        cd commandline
+        make CC=aarch64-linux-gnu-gcc
+
+    - name: install macOS dependencies and run make
+      if: runner.os == 'macOS'
+      run: |
+        brew install libusb-compat # libusb is installed too for libusb-compat
+        LIBUSB_PREFIX=$(brew --prefix libusb-compat)
+        PKG_CONFIG_PATH=$LIBUSB_PREFIX/lib/pkgconfig
+        echo PKG_CONFIG_PATH=$PKG_CONFIG_PATH
+        cd commandline
+        echo make USBFLAGS="$(pkg-config --cflags libusb)"
+        make USBFLAGS="$(pkg-config --cflags libusb)"
+        ls -l
+
+    - name: Install Windows i686 build system
+      if: runner.os == 'Windows' && matrix.target-dir == 'i686-mingw32'
+      uses: msys2/setup-msys2@v2
+      with:
+        msystem: MINGW64
+        #install: git base-devel binutils mingw-w64-x86_64-toolchain make zip mingw-w64-x86_64-libusb-win32
+        install: git base-devel mingw-w64-i686-toolchain zip mingw-w64-i686-libusb-win32
+        update: true
+
+    - name: make i686 Windows exe
+      if: runner.os == 'Windows' && matrix.target-dir == 'i686-mingw32'
+      run: |
+        TARGET_DIR=${{ matrix.target-dir }}
+        cd commandline
+        PATH="/mingw32/bin:$PATH"
+        mingw32-make
+        if [[ ! -d builds/$TARGET_DIR/ ]]; then mkdir builds/$TARGET_DIR; fi
+        echo mv micronucleus.exe builds/$TARGET_DIR
+        mv micronucleus.exe builds/$TARGET_DIR
+        echo cp -p /mingw32/bin/libusb*.dll builds/$TARGET_DIR
+        cp -p /mingw32/bin/libusb*.dll builds/$TARGET_DIR
+
+    - name: Install Windows x86_64 build system
+      if: runner.os == 'Windows' && matrix.target-dir == 'x86_64-mingw32'
       uses: msys2/setup-msys2@v2
       with:
         msystem: MINGW64
         install: git base-devel binutils mingw-w64-x86_64-toolchain make zip mingw-w64-x86_64-libusb-win32
         update: true
-      if: runner.os == 'Windows'
 
-    - name: install macOS dependencies
+    - name: make x86_64 Windows exe
+      if: runner.os == 'Windows' && matrix.target-dir == 'x86_64-mingw32'
       run: |
-        brew install libusb-compat
-        LIBUSB_PREFIX=$(brew --prefix libusb-compat)
-        PKG_CONFIG_PATH=$LIBUSB_PREFIX/lib/pkgconfig
-        echo PKG_CONFIG_PATH=$PKG_CONFIG_PATH
-        echo "find $(brew --prefix libusb-compat)/lib -name "*dylib" -type f -depth 1"
-        find $(brew --prefix libusb-compat)/lib -name "*dylib" -type f -depth 1
-        cd commandline
-        echo make USBFLAGS="$(pkg-config --cflags libusb)" USBLIBS="$(pkg-config --libs libusb)"
-        make USBFLAGS="$(pkg-config --cflags libusb)" USBLIBS="$(pkg-config --libs libusb)"
-        TARGET_DIR=Darwin-x86_64
-        if [[ ! -d builds/$TARGET_DIR/ ]]; then mkdir builds/$TARGET_DIR; fi
-        mv micronucleus builds/$TARGET_DIR
-        EXTRALIB=$(find $(brew --prefix libusb-compat)/lib -name "*dylib" -type f -depth 1)
-        cp -p $EXTRALIB builds/$TARGET_DIR
-      shell: bash {0} # Required to avoid an exit at first error
-      if: runner.os == 'macOS'
-
-    - name: make windows
-      id: make
-      run: |
+        TARGET_DIR=${{ matrix.target-dir }}
         cd commandline
         mingw32-make
-        TARGET_DIR=Windows
         if [[ ! -d builds/$TARGET_DIR/ ]]; then mkdir builds/$TARGET_DIR; fi
-        cp -p /mingw64/bin/libusb*.dll builds/$TARGET_DIR; fi
-      shell: bash {0} # Required to avoid an exit at first error
-      if: runner.os == 'Windows'
+        echo mv micronucleus.exe builds/$TARGET_DIR
+        mv micronucleus.exe builds/$TARGET_DIR
+        echo cp -p /mingw64/bin/libusb*.dll builds/$TARGET_DIR
+        cp -p /mingw64/bin/libusb*.dll builds/$TARGET_DIR
 
-    - name: Commit files
+    - name: create tarballs and move them to builds directory
+      if: runner.os != 'Windows'
       run: |
-        git config --local user.email "github-actions[bot]@users.noreply.github.com"
-        git config --local user.name "github-actions[bot]"
-        echo git status
-        git status
-        echo git commit --amend --no-edit --verbose commandline/builds/*/micronucleus*
-        git commit --amend --no-edit --verbose commandline/builds/*/micronucleus*
-        git pull origin ${{github.ref}} --rebase --verbose
+        TARGET_DIR=${{ matrix.target-dir }}
+        TARBALL_NAME=micronucleus-cli-2.5-$TARGET_DIR.tar.gz
+        TARBALL_NAME_PIO=micronucleus-cli-2.5-pio-$TARGET_DIR.tar.gz
+        set -o verbose
+        mkdir micronucleus # temporary tar directory
+        chmod +x commandline/micronucleus
+        mv commandline/micronucleus micronucleus
+        tar -czvf $TARBALL_NAME micronucleus # create arduino tarball
+        cp commandline/builds/$TARGET_DIR/package.json micronucleus
+        cd micronucleus
+        tar -czvf $TARBALL_NAME_PIO micronucleus package.json # create PIO tarball
+        ls -l
 
-    - name: Push binaries back to repo
-      uses: ad-m/github-push-action@master
-      with:
-        github_token: ${{ secrets.GITHUB_TOKEN }}
-        directory: commandline
-        force: true
+        cd ../commandline
+        set +o verbose
+        if [[ ! -d builds/$TARGET_DIR/ ]]; then
+          # build new directory
+          mkdir builds/$TARGET_DIR
+        fi
+
+        ls -l builds/$TARGET_DIR # show old content which we had checked out
+        # process Arduino tarball
+        if [[ ! -e builds/$TARGET_DIR/$TARBALL_NAME ]]; then
+          echo mv ../$TARBALL_NAME builds/$TARGET_DIR
+          mv ../$TARBALL_NAME builds/$TARGET_DIR
+          echo git -add builds/$TARGET_DIR/$TARBALL_NAME
+          git add builds/$TARGET_DIR/$TARBALL_NAME
+        else
+          echo mv ../$TARBALL_NAME builds/$TARGET_DIR
+          mv ../$TARBALL_NAME builds/$TARGET_DIR
+        fi
+
+        # process PIO tarball
+        if [[ ! -e builds/$TARGET_DIR/$TARBALL_NAME_PIO ]]; then
+          echo mv ../micronucleus/$TARBALL_NAME_PIO builds/$TARGET_DIR
+          mv ../micronucleus/$TARBALL_NAME_PIO builds/$TARGET_DIR
+          echo git -add builds/$TARGET_DIR/$TARBALL_NAME_PIO
+          git add builds/$TARGET_DIR/$TARBALL_NAME_PIO
+        else
+          echo mv ../micronucleus/$TARBALL_NAME_PIO builds/$TARGET_DIR
+          mv ../micronucleus/$TARBALL_NAME_PIO builds/$TARGET_DIR
+        fi
+        # show new content
+        ls -l builds/$TARGET_DIR
+
+    - name: Commit and push files
+      run: |
+        TARGET_DIR=${{ matrix.target-dir }}
+        cd commandline/builds/$TARGET_DIR
+        ls -l
+        #echo GITHUB_ACTOR=$GITHUB_ACTOR # the one who made the commit which started this workflow
+        git config user.name "$GITHUB_ACTOR"
+        git config user.email "github-actions[bot]@users.noreply.github.com"
+
+        #echo git status:
+        #git status
+        echo git commit --message=\"exetutable for $TARGET_DIR\" --verbose micronucleus*
+        git commit --message="exetutable for $TARGET_DIR" --verbose micronucleus*
+        # Amend does not work for me :-(
+        #git commit --amend --no-edit --verbose micronucleus*
+        if [ $? -ne 0 ]; then
+          echo "nothing to commit"
+          exit 0
+        fi
+
+        # required to rebase with the push results of the parallel jobs
+        # Lets hope that we do not run into a race condition between pull and push
+        #echo git pull --ff-only --verbose
+        #git pull --ff-only --verbose
+        echo git pull --verbose
+        git pull --verbose
+
+        # not required for us
+        #repo_uri="https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
+        #git remote set-url "$remote_name" "$repo_uri" # includes access token
+        #git push --force origin ${{github.ref}}
+
+        echo git push
+        git push
+        if [[ $? -ne 0 ]]; then
+          # try 4 times with random delays
+          for ((i = 0 ; i < 4 ; i++)); do
+            RETRY_DELAY=$[ ( $RANDOM % 10 )  + 10 ]
+            echo "Race condition, retry in ${RETRY_DELAY} seconds"
+            sleep ${RETRY_DELAY}s
+            echo git pull
+            git pull
+            echo git push
+            git push
+            if [[ $? -eq 0 ]]; then break; fi
+          done
+        fi
